{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "securefs.fullname" . }}
  labels:
    {{- include "securefs.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: {{ .Values.secrets.dbPass | quote }}
  DATA_KEY: {{ .Values.secrets.dataKey | quote }}
  DB_CONN_PASSWORD: {{ .Values.secrets.dbConnPassword | default .Values.secrets.dbPass | quote }}
  {{- if and (eq .Values.storage.backend "s3") .Values.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- end }}
{{- end }}
